const {Survey} = require("../models")

const surveyData = [
    {
        user_id: 1,
        birthdate: "1980-04-29",
        gender: "Male",
        pref_gender: "Female",
        bio: "This is where someone will talk about themselves.",
        relationship: "Marriage and kids",
        goal: "Long-term relationship",
        language: "JavaScript",
        type: "Web Developer",
        worker: "Work and energy drinks all night, everynight",
        ideal_date: "Stay in, get takeout, watch a movie or play video games",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835948/beybv9cgzva6chkxxsdz.png"
    },
    {
        user_id: 2,
        birthdate: "1982-01-04",
        gender: "Male",
        pref_gender: "Male",
        bio: "This is where someone will talk about themselves.",
        relationship: "Marriage but no kids",
        goal: "Just looking for something casual",
        language: "C++",
        type: "Web Developer",
        worker: "Hard worker but I need my social life balance",
        ideal_date: "Go out to a nice restaurant or picnic and stare into each other’s eyes",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835948/co9qy8vxbf2qhc3knea3.png"
    },
    {
        user_id: 3,
        birthdate: "1992-03-20",
        gender: "Male",
        pref_gender: "Both",
        bio: "This is where someone will talk about themselves.",
        relationship: "Kids but no marital commitment",
        goal: "I need programming help",
        language: "Python",
        type: "Web Developer",
        worker: "Bare minimum to get the work done then do other hobbies",
        ideal_date: "Go out with a group of friends for a game night or drinks",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835948/pwrcttkasibmy1tkt7i2.png"
    },
    {
        user_id: 4,
        birthdate: "1998-06-14",
        gender: "Female",
        pref_gender: "Male",
        bio: "This is where someone will talk about themselves.",
        relationship: "None of the above",
        goal: "None of the above",
        language: "HTML",
        type: "Web Developer",
        worker: "None of the above",
        ideal_date: "Hit the club, take some shots, initiate the bender",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835948/xeloqi1url6heip5ny3f.png"
    },
    {
        user_id: 5,
        birthdate: "1999-04-08",
        gender: "Female",
        pref_gender: "Female",
        bio: "This is where someone will talk about themselves.",
        relationship: "Marriage and kids",
        goal: "Long-term relationship",
        language: "JavaScript",
        type: "Web Developer",
        worker: "Work and energy drinks all night, everynight",
        ideal_date: "Stay in, get takeout, watch a movie or play video games",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835947/te0jqgb9bvpalebnfk3d.png"
    },
    {
        user_id: 6,
        birthdate: "2000-10-06",
        gender: "Female",
        pref_gender: "Both",
        bio: "This is where someone will talk about themselves.",
        relationship: "Marriage but no kids",
        goal: "Just looking for something casual",
        language: "C++",
        type: "Web Developer",
        worker: "Hard worker but I need my social life balance",
        ideal_date: "Go out to a nice restaurant or picnic and stare into each other’s eyes",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835945/opboe2847jkdgqtekmpf.png"
    },
    {
        user_id: 7,
        birthdate: "1983-09-29",
        gender: "Male",
        pref_gender: "Male",
        bio: "This is where someone will talk about themselves.",
        relationship: "Kids but no marital commitment",
        goal: "I need programming help",
        language: "Python",
        type: "Web Developer",
        worker: "Bare minimum to get the work done then do other hobbies",
        ideal_date: "Go out with a group of friends for a game night or drinks",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835945/jelvqartpd6lwmav6v0d.png"
    },
    {
        user_id: 8,
        birthdate: "1985-08-04",
        gender: "Female",
        pref_gender: "Female",
        bio: "This is where someone will talk about themselves.",
        relationship: "None of the above",
        goal: "None of the above",
        language: "HTML",
        type: "Web Developer",
        worker: "None of the above",
        ideal_date: "Hit the club, take some shots, initiate the bender",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835948/xeloqi1url6heip5ny3f.png"
    },
    {
        user_id: 9,
        birthdate: "1985-08-22",
        gender: "Male",
        pref_gender: "Female",
        bio: "This is where someone will talk about themselves.",
        relationship: "None of the above",
        goal: "None of the above",
        language: "HTML",
        type: "Web Developer",
        worker: "None of the above",
        ideal_date: "Hit the club, take some shots, initiate the bender",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835948/xeloqi1url6heip5ny3f.png"
    },
    {
        user_id: 10,
        birthdate: "1994-07-23",
        gender: "Male",
        pref_gender: "Male",
        bio: "This is where someone will talk about themselves.",
        relationship: "None of the above",
        goal: "None of the above",
        language: "HTML",
        type: "Web Developer",
        worker: "None of the above",
        ideal_date: "Hit the club, take some shots, initiate the bender",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835945/jelvqartpd6lwmav6v0d.png"
    },
    {
        user_id: 11,
        birthdate: "1994-11-13",
        gender: "Female",
        pref_gender: "Male",
        bio: "This is where someone will talk about themselves.",
        relationship: "None of the above",
        goal: "None of the above",
        language: "HTML",
        type: "Web Developer",
        worker: "None of the above",
        ideal_date: "Hit the club, take some shots, initiate the bender",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835945/opboe2847jkdgqtekmpf.png"
    },
    {
        user_id: 12,
        birthdate: "2000-12-20",
        gender: "Female",
        pref_gender: "Female",
        bio: "This is where someone will talk about themselves.",
        relationship: "None of the above",
        goal: "None of the above",
        language: "HTML",
        type: "Web Developer",
        worker: "None of the above",
        ideal_date: "Hit the club, take some shots, initiate the bender",
        profile_pic: "https://res.cloudinary.com/coder-mingle/image/upload/v1635835947/te0jqgb9bvpalebnfk3d.png"
    }
]

const seedSurvey = () => Survey.bulkCreate(surveyData)

module.exports = seedSurvey